"""
Unified team-name translation between three naming systems:
  • Odds API   – e.g. "Alabama Crimson Tide"
  • KenPom     – e.g. "Alabama" (uses "St." abbreviations)
  • ELO / SportsRef – e.g. "Alabama" (uses full "State")

Usage:
    from name_maps import odds_to_kenpom, kenpom_to_elo, elo_to_kenpom
"""

# ── Odds API full name  →  KenPom short name ────────────────────────────────
# This is the single source of truth.  Every team the Odds API might return
# should have an entry here (or the fallback just strips the mascot).

_ODDS_TO_KENPOM: dict[str, str] = {
    # A
    "Abilene Christian Wildcats": "Abilene Christian",
    "Air Force Falcons": "Air Force",
    "Akron Zips": "Akron",
    "Alabama Crimson Tide": "Alabama",
    "American Eagles": "American",
    "Appalachian St Mountaineers": "Appalachian St.",
    "Arizona Wildcats": "Arizona",
    "Arizona St Sun Devils": "Arizona St.",
    "Arkansas Razorbacks": "Arkansas",
    "Arkansas St Red Wolves": "Arkansas St.",
    "Arkansas-Little Rock Trojans": "Little Rock",
    "Army Knights": "Army",
    "Auburn Tigers": "Auburn",
    # B
    "BYU Cougars": "BYU",
    "Ball State Cardinals": "Ball St.",
    "Baylor Bears": "Baylor",
    "Boise State Broncos": "Boise St.",
    "Boston College Eagles": "Boston College",
    "Boston Univ. Terriers": "Boston University",
    "Bowling Green Falcons": "Bowling Green",
    "Brown Bears": "Brown",
    "Buffalo Bulls": "Buffalo",
    # C
    "CSU Bakersfield Roadrunners": "Cal St. Bakersfield",
    "CSU Fullerton Titans": "Cal St. Fullerton",
    "CSU Northridge Matadors": "CSUN",
    "Cal Baptist Lancers": "Cal Baptist",
    "Cal Poly Mustangs": "Cal Poly",
    "California Golden Bears": "California",
    "Campbell Fighting Camels": "Campbell",
    "Canisius Golden Griffins": "Canisius",
    "Central Arkansas Bears": "Central Arkansas",
    "Central Connecticut St Blue Devils": "Central Connecticut",
    "Central Michigan Chippewas": "Central Michigan",
    "Charleston Southern Buccaneers": "Charleston Southern",
    "Chattanooga Mocs": "Chattanooga",
    "Cincinnati Bearcats": "Cincinnati",
    "Clemson Tigers": "Clemson",
    "Cleveland St Vikings": "Cleveland St.",
    "Coastal Carolina Chanticleers": "Coastal Carolina",
    "Colorado Buffaloes": "Colorado",
    "Colorado St Rams": "Colorado St.",
    "Columbia Lions": "Columbia",
    "Cornell Big Red": "Cornell",
    "Creighton Bluejays": "Creighton",
    # D
    "Dartmouth Big Green": "Dartmouth",
    "Dayton Flyers": "Dayton",
    "Delaware Blue Hens": "Delaware",
    "Detroit Mercy Titans": "Detroit Mercy",
    "Duke Blue Devils": "Duke",
    "Duquesne Dukes": "Duquesne",
    # E
    "East Tennessee St Buccaneers": "East Tennessee St.",
    "Eastern Illinois Panthers": "Eastern Illinois",
    "Eastern Washington Eagles": "Eastern Washington",
    "Elon Phoenix": "Elon",
    "Evansville Purple Aces": "Evansville",
    # F
    "Fairfield Stags": "Fairfield",
    "Florida Gators": "Florida",
    "Florida Int'l Golden Panthers": "FIU",
    "Florida St Seminoles": "Florida St.",
    "Fordham Rams": "Fordham",
    "Fort Wayne Mastodons": "Purdue Fort Wayne",
    "Fresno St Bulldogs": "Fresno St.",
    "Furman Paladins": "Furman",
    # G
    "GW Revolutionaries": "George Washington",
    "George Mason Patriots": "George Mason",
    "Georgetown Hoyas": "Georgetown",
    "Georgia Bulldogs": "Georgia",
    "Georgia Southern Eagles": "Georgia Southern",
    "Georgia St Panthers": "Georgia St.",
    "Georgia Tech Yellow Jackets": "Georgia Tech",
    "Gonzaga Bulldogs": "Gonzaga",
    "Grand Canyon Antelopes": "Grand Canyon",
    "Green Bay Phoenix": "Green Bay",
    # H
    "Hampton Pirates": "Hampton",
    "Harvard Crimson": "Harvard",
    "Hawai'i Rainbow Warriors": "Hawaii",
    "Hofstra Pride": "Hofstra",
    "Holy Cross Crusaders": "Holy Cross",
    "Houston Cougars": "Houston",
    # I
    "IUPUI Jaguars": "IU Indy",
    "Idaho State Bengals": "Idaho St.",
    "Idaho Vandals": "Idaho",
    "Illinois Fighting Illini": "Illinois",
    "Incarnate Word Cardinals": "Incarnate Word",
    "Iona Gaels": "Iona",
    "Iowa Hawkeyes": "Iowa",
    "Iowa State Cyclones": "Iowa St.",
    # J
    "Jacksonville St Gamecocks": "Jacksonville St.",
    "James Madison Dukes": "James Madison",
    # K
    "Kansas Jayhawks": "Kansas",
    "Kansas St Wildcats": "Kansas St.",
    "Kennesaw St Owls": "Kennesaw St.",
    "Kent State Golden Flashes": "Kent St.",
    "Kentucky Wildcats": "Kentucky",
    # L
    "LSU Tigers": "LSU",
    "Lafayette Leopards": "Lafayette",
    "Lamar Cardinals": "Lamar",
    "Liberty Flames": "Liberty",
    "Lindenwood Lions": "Lindenwood",
    "Long Beach St 49ers": "Long Beach St.",
    "Louisiana Ragin Cajuns": "Louisiana",
    "Louisiana Ragin' Cajuns": "Louisiana",
    "Louisiana Tech Bulldogs": "Louisiana Tech",
    "Louisville Cardinals": "Louisville",
    "Loyola (Chi) Ramblers": "Loyola Chicago",
    "Loyola (MD) Greyhounds": "Loyola MD",
    "Loyola Marymount Lions": "Loyola Marymount",
    # M
    "Manhattan Jaspers": "Manhattan",
    "Marshall Thundering Herd": "Marshall",
    "Massachusetts Minutemen": "Massachusetts",
    "McNeese Cowboys": "McNeese",
    "Mercer Bears": "Mercer",
    "Mercyhurst Lakers": "Mercyhurst",
    "Merrimack Warriors": "Merrimack",
    "Miami Hurricanes": "Miami FL",
    "Miami (OH) RedHawks": "Miami OH",
    "Michigan Wolverines": "Michigan",
    "Michigan St Spartans": "Michigan St.",
    "Middle Tennessee Blue Raiders": "Middle Tennessee",
    "Minnesota Golden Gophers": "Minnesota",
    "Mississippi St Bulldogs": "Mississippi St.",
    "Missouri St Bears": "Missouri St.",
    "Missouri Tigers": "Missouri",
    "Monmouth Hawks": "Monmouth",
    "Montana Grizzlies": "Montana",
    "Montana St Bobcats": "Montana St.",
    "Mt. St. Marys Mountaineers": "Mount St. Mary's",
    # N
    "N Colorado Bears": "Northern Colorado",
    "NC State Wolfpack": "N.C. State",
    "Nebraska Cornhuskers": "Nebraska",
    "Nevada Wolf Pack": "Nevada",
    "New Mexico Lobos": "New Mexico",
    "New Mexico St Aggies": "New Mexico St.",
    "New Orleans Privateers": "New Orleans",
    "Niagara Purple Eagles": "Niagara",
    "North Carolina Tar Heels": "North Carolina",
    "North Carolina A&T Aggies": "North Carolina A&T",
    "North Dakota Fighting Hawks": "North Dakota",
    "North Dakota St Bison": "North Dakota St.",
    "Northeastern Huskies": "Northeastern",
    "Northern Arizona Lumberjacks": "Northern Arizona",
    "Northern Illinois Huskies": "Northern Illinois",
    "Northern Kentucky Norse": "Northern Kentucky",
    "Northwestern Wildcats": "Northwestern",
    "Notre Dame Fighting Irish": "Notre Dame",
    # O
    "Oakland Golden Grizzlies": "Oakland",
    "Ohio Bobcats": "Ohio",
    "Ohio St Buckeyes": "Ohio St.",
    "Oklahoma Sooners": "Oklahoma",
    "Oklahoma St Cowboys": "Oklahoma St.",
    "Old Dominion Monarchs": "Old Dominion",
    "Ole Miss Rebels": "Mississippi",
    "Omaha Mavericks": "Nebraska Omaha",
    "Oral Roberts Golden Eagles": "Oral Roberts",
    "Oregon Ducks": "Oregon",
    "Oregon St Beavers": "Oregon St.",
    # P
    "Pacific Tigers": "Pacific",
    "Penn State Nittany Lions": "Penn St.",
    "Pennsylvania Quakers": "Penn",
    "Pepperdine Waves": "Pepperdine",
    "Pittsburgh Panthers": "Pittsburgh",
    "Portland Pilots": "Portland",
    "Portland St Vikings": "Portland St.",
    "Princeton Tigers": "Princeton",
    "Providence Friars": "Providence",
    "Purdue Boilermakers": "Purdue",
    # Q
    "Queens University Royals": "Queens",
    "Quinnipiac Bobcats": "Quinnipiac",
    # R
    "Rhode Island Rams": "Rhode Island",
    "Richmond Spiders": "Richmond",
    "Rider Broncs": "Rider",
    "Robert Morris Colonials": "Robert Morris",
    # S
    "SE Missouri St Redhawks": "Southeast Missouri",
    "SIU-Edwardsville Cougars": "SIUE",
    "SMU Mustangs": "SMU",
    "Sacred Heart Pioneers": "Sacred Heart",
    "Sacramento St Hornets": "Sacramento St.",
    "Saint Josephs Hawks": "Saint Joseph's",
    "Saint Joseph's Hawks": "Saint Joseph's",
    "Saint Louis Billikens": "Saint Louis",
    "Saint Mary's Gaels": "Saint Mary's",
    "Saint Peters Peacocks": "Saint Peter's",
    "Sam Houston St Bearkats": "Sam Houston St.",
    "Samford Bulldogs": "Samford",
    "San Diego St Aztecs": "San Diego St.",
    "San Diego Toreros": "San Diego",
    "San Francisco Dons": "San Francisco",
    "San Jose St Spartans": "San Jose St.",
    "San José St Spartans": "San Jose St.",
    "Santa Clara Broncos": "Santa Clara",
    "Seattle Redhawks": "Seattle",
    "Seton Hall Pirates": "Seton Hall",
    "Siena Saints": "Siena",
    "South Alabama Jaguars": "South Alabama",
    "South Carolina Gamecocks": "South Carolina",
    "South Dakota Coyotes": "South Dakota",
    "South Dakota St Jackrabbits": "South Dakota St.",
    "Southern Indiana Screaming Eagles": "Southern Indiana",
    "Southern Miss Golden Eagles": "Southern Miss",
    "Southern Utah Thunderbirds": "Southern Utah",
    "St. Bonaventure Bonnies": "St. Bonaventure",
    "St. Francis (PA) Red Flash": "Saint Francis",
    "St. John's Red Storm": "St. John's",
    "St. Johns Red Storm": "St. John's",
    "St. Thomas (MN) Tommies": "St. Thomas",
    "Stanford Cardinal": "Stanford",
    "Stonehill Skyhawks": "Stonehill",
    "Stony Brook Seawolves": "Stony Brook",
    "Syracuse Orange": "Syracuse",
    # T
    "TCU Horned Frogs": "TCU",
    "Tarleton State Texans": "Tarleton St.",
    "Tenn-Martin Skyhawks": "Tennessee Martin",
    "Tennessee Volunteers": "Tennessee",
    "Tennessee St Tigers": "Tennessee St.",
    "Tennessee Tech Golden Eagles": "Tennessee Tech",
    "Texas Longhorns": "Texas",
    "Texas A&M Aggies": "Texas A&M",
    "Texas St Bobcats": "Texas St.",
    "Texas State Bobcats": "Texas St.",
    "Texas Tech Red Raiders": "Texas Tech",
    "The Citadel Bulldogs": "The Citadel",
    "Toledo Rockets": "Toledo",
    "Towson Tigers": "Towson",
    "Troy Trojans": "Troy",
    # U
    "UC Irvine Anteaters": "UC Irvine",
    "UC Riverside Highlanders": "UC Riverside",
    "UC San Diego Tritons": "UC San Diego",
    "UC Santa Barbara Gauchos": "UC Santa Barbara",
    "UCF Knights": "UCF",
    "UCLA Bruins": "UCLA",
    "UConn Huskies": "Connecticut",
    "UL Monroe Warhawks": "Louisiana Monroe",
    "UMBC Retrievers": "UMBC",
    "UMKC Kangaroos": "Kansas City",
    "UMass Lowell River Hawks": "UMass Lowell",
    "UNC Asheville Bulldogs": "UNC Asheville",
    "UNC Greensboro Spartans": "UNC Greensboro",
    "UNLV Rebels": "UNLV",
    "USC Trojans": "USC",
    "UTEP Miners": "UTEP",
    "Utah Utes": "Utah",
    "Utah State Aggies": "Utah St.",
    "Utah Tech Trailblazers": "Utah Tech",
    "Utah Valley Wolverines": "Utah Valley",
    # V
    "VMI Keydets": "VMI",
    "VCU Rams": "VCU",
    "Valparaiso Beacons": "Valparaiso",
    "Vanderbilt Commodores": "Vanderbilt",
    "Villanova Wildcats": "Villanova",
    "Virginia Cavaliers": "Virginia",
    "Virginia Tech Hokies": "Virginia Tech",
    # W
    "Wake Forest Demon Deacons": "Wake Forest",
    "Washington Huskies": "Washington",
    "Washington St Cougars": "Washington St.",
    "Weber State Wildcats": "Weber St.",
    "West Virginia Mountaineers": "West Virginia",
    "Western Carolina Catamounts": "Western Carolina",
    "Western Illinois Leathernecks": "Western Illinois",
    "Western Kentucky Hilltoppers": "Western Kentucky",
    "Western Michigan Broncos": "Western Michigan",
    "William & Mary Tribe": "William & Mary",
    "Wisconsin Badgers": "Wisconsin",
    "Wofford Terriers": "Wofford",
    "Wright St Raiders": "Wright St.",
    "Wyoming Cowboys": "Wyoming",
    # X-Y
    "Xavier Musketeers": "Xavier",
    "Yale Bulldogs": "Yale",
    "Youngstown St Penguins": "Youngstown St.",
}

# ── KenPom name  ↔  ELO / Sports-Reference name ─────────────────────────────
# Only entries where the two systems disagree (mostly "St." vs "State").
_KENPOM_TO_ELO: dict[str, str] = {
    "Appalachian St.": "Appalachian State",
    "Arizona St.": "Arizona State",
    "Arkansas St.": "Arkansas State",
    "Alabama St.": "Alabama State",
    "Alcorn St.": "Alcorn State",
    "Ball St.": "Ball State",
    "Boise St.": "Boise State",
    "Cal St. Bakersfield": "Cal State Bakersfield",
    "Cal St. Fullerton": "Cal State Fullerton",
    "CSUN": "Cal State Northridge",
    "Chicago St.": "Chicago State",
    "Cleveland St.": "Cleveland State",
    "Colorado St.": "Colorado State",
    "Coppin St.": "Coppin State",
    "Delaware St.": "Delaware State",
    "East Tennessee St.": "East Tennessee State",
    "Florida St.": "Florida State",
    "Fresno St.": "Fresno State",
    "Georgia St.": "Georgia State",
    "Grambling St.": "Grambling State",
    "Idaho St.": "Idaho State",
    "Illinois St.": "Illinois State",
    "Indiana St.": "Indiana State",
    "Iowa St.": "Iowa State",
    "Jackson St.": "Jackson State",
    "Jacksonville St.": "Jacksonville State",
    "Kansas St.": "Kansas State",
    "Kennesaw St.": "Kennesaw State",
    "Kent St.": "Kent State",
    "Long Beach St.": "Long Beach State",
    "LSU": "Louisiana State",
    "Michigan St.": "Michigan State",
    "Mississippi": "Ole Miss",
    "Mississippi St.": "Mississippi State",
    "Mississippi Valley St.": "Mississippi Valley State",
    "Missouri St.": "Missouri State",
    "Montana St.": "Montana State",
    "Morehead St.": "Morehead State",
    "Morgan St.": "Morgan State",
    "Murray St.": "Murray State",
    "N.C. State": "NC State",
    "New Mexico St.": "New Mexico State",
    "Norfolk St.": "Norfolk State",
    "North Dakota St.": "North Dakota State",
    "Northwestern St.": "Northwestern State",
    "Ohio St.": "Ohio State",
    "Oklahoma St.": "Oklahoma State",
    "Oregon St.": "Oregon State",
    "Penn St.": "Penn State",
    "Portland St.": "Portland State",
    "Sacramento St.": "Sacramento State",
    "Sam Houston St.": "Sam Houston State",
    "San Diego St.": "San Diego State",
    "San Jose St.": "San Jose State",
    "South Carolina St.": "South Carolina State",
    "South Dakota St.": "South Dakota State",
    "Southeast Missouri": "Southeast Missouri State",
    "Southern Miss": "Southern Mississippi",
    "SIUE": "SIU Edwardsville",
    "Tarleton St.": "Tarleton State",
    "Tennessee St.": "Tennessee State",
    "Texas St.": "Texas State",
    "Utah St.": "Utah State",
    "Washington St.": "Washington State",
    "Weber St.": "Weber State",
    "Wichita St.": "Wichita State",
    "Wright St.": "Wright State",
    "Youngstown St.": "Youngstown State",
    # Non-"State" mismatches (only ones present in original elo_name_map)
    "Miami FL": "Miami (FL)",
    "Miami OH": "Miami (OH)",
    "Saint Mary's": "St. Mary's (CA)",
    "Louisiana Monroe": "Louisiana-Monroe",
    "BYU": "Brigham Young",
    "Massachusetts": "UMass",
    "Albany": "Albany (NY)",
    "Illinois Chicago": "Illinois-Chicago",
}

# Build the reverse map once
_ELO_TO_KENPOM: dict[str, str] = {v: k for k, v in _KENPOM_TO_ELO.items()}

# Also build a harmonize map for KenPom CSV loading (Sports-Ref style → KenPom)
# This is the same as _ELO_TO_KENPOM plus a few extra aliases that appear in the
# KenPom CSV itself with full "State" spelling.
KENPOM_CSV_HARMONIZE: dict[str, str] = {
    "Alabama State": "Alabama St.",
    "Alcorn State": "Alcorn St.",
    "Appalachian State": "Appalachian St.",
    "Arizona State": "Arizona St.",
    "Arkansas State": "Arkansas St.",
    "Ball State": "Ball St.",
    "Boise State": "Boise St.",
    "Cal State Bakersfield": "Cal St. Bakersfield",
    "Cal State Fullerton": "Cal St. Fullerton",
    "Cal State Northridge": "CSUN",
    "Central Connecticut State": "Central Connecticut",
    "Chicago State": "Chicago St.",
    "Cleveland State": "Cleveland St.",
    "Colorado State": "Colorado St.",
    "Coppin State": "Coppin St.",
    "Delaware State": "Delaware St.",
    "East Tennessee State": "East Tennessee St.",
    "Florida State": "Florida St.",
    "Fresno State": "Fresno St.",
    "Georgia State": "Georgia St.",
    "Grambling State": "Grambling St.",
    "Idaho State": "Idaho St.",
    "Illinois State": "Illinois St.",
    "Indiana State": "Indiana St.",
    "Iowa State": "Iowa St.",
    "Jackson State": "Jackson St.",
    "Jacksonville State": "Jacksonville St.",
    "Kansas State": "Kansas St.",
    "Kennesaw State": "Kennesaw St.",
    "Kent State": "Kent St.",
    "Long Beach State": "Long Beach St.",
    "Louisiana State": "LSU",
    "McNeese State": "McNeese",
    "Michigan State": "Michigan St.",
    "Mississippi State": "Mississippi St.",
    "Mississippi Valley State": "Mississippi Valley St.",
    "Missouri State": "Missouri St.",
    "Montana State": "Montana St.",
    "Morehead State": "Morehead St.",
    "Morgan State": "Morgan St.",
    "Murray State": "Murray St.",
    "NC State": "N.C. State",
    "New Mexico State": "New Mexico St.",
    "Nicholls State": "Nicholls",
    "Norfolk State": "Norfolk St.",
    "North Dakota State": "North Dakota St.",
    "Northwestern State": "Northwestern St.",
    "Ohio State": "Ohio St.",
    "Oklahoma State": "Oklahoma St.",
    "Oregon State": "Oregon St.",
    "Penn State": "Penn St.",
    "Portland State": "Portland St.",
    "Sacramento State": "Sacramento St.",
    "Sam Houston State": "Sam Houston St.",
    "San Diego State": "San Diego St.",
    "San Jose State": "San Jose St.",
    "South Carolina State": "South Carolina St.",
    "South Dakota State": "South Dakota St.",
    "Southeast Missouri State": "Southeast Missouri",
    "Southern Mississippi": "Southern Miss",
    "SIU Edwardsville": "SIUE",
    "Tarleton State": "Tarleton St.",
    "Tennessee State": "Tennessee St.",
    "Texas State": "Texas St.",
    "Utah State": "Utah St.",
    "Washington State": "Washington St.",
    "Weber State": "Weber St.",
    "Wichita State": "Wichita St.",
    "Wright State": "Wright St.",
    "Youngstown State": "Youngstown St.",
    "Ole Miss": "Mississippi",
    "Illinois-Chicago": "Illinois Chicago",
    "St. John's (NY)": "St. John's",
    "Miami (FL)": "Miami FL",
    "Miami (OH)": "Miami OH",
    "St. Mary's (CA)": "Saint Mary's",
    "Texas A&M-Corpus Christi": "Texas A&M Corpus Chris",
    "Louisiana-Monroe": "Louisiana Monroe",
    "Arkansas-Pine Bluff": "Arkansas Pine Bluff",
    "Texas-Rio Grande Valley": "UT Rio Grande Valley",
    "Albany (NY)": "Albany",
    "Brigham Young": "BYU",
    "UMass": "Massachusetts",
    "Gardner-Webb": "Gardner Webb",
    "College of Charleston": "Charleston",
}


# ── Public helpers ───────────────────────────────────────────────────────────

def odds_to_kenpom(name: str) -> str:
    """Translate an Odds API team name to its KenPom equivalent."""
    return _ODDS_TO_KENPOM.get(name, name)


def kenpom_to_elo(name: str) -> str:
    """Translate a KenPom name to the ELO / Sports-Reference name."""
    return _KENPOM_TO_ELO.get(name, name)


def elo_to_kenpom(name: str) -> str:
    """Translate an ELO / Sports-Reference name to KenPom."""
    return _ELO_TO_KENPOM.get(name, name)
